# Generated by Django 3.1.5 on 2022-01-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=25, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('phone_num', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('user_pass', models.CharField(blank=True, max_length=50, null=True)),
                ('isAdmin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Users',
                'managed': True,
            },
        ),
    ]
