# Generated by Django 3.1.5 on 2022-01-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_varified',
            field=models.BooleanField(default=False),
        ),
    ]
