# Generated by Django 3.1.5 on 2022-01-18 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_phone_varified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_varified',
            new_name='phone_verified',
        ),
    ]
