# Generated by Django 3.1.5 on 2022-01-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20220118_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify_pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
