# Generated by Django 3.1.5 on 2022-01-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_user_verify_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
