# Generated by Django 3.1.5 on 2022-01-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_user_image_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to='portraits'),
        ),
    ]
