# Generated by Django 3.1.5 on 2022-01-19 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
    ]
