# Generated by Django 3.1.5 on 2022-01-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20220120_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_target',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
