# Generated by Django 3.1.5 on 2022-01-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20220122_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kills_this_round',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
