# Generated by Django 3.1.5 on 2022-02-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_user_kills_this_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_kills',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='kills_this_round',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
