# Generated by Django 3.1.5 on 2022-02-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20220208_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alive',
            field=models.BooleanField(default=True),
        ),
    ]
