# Generated by Django 3.1.5 on 2022-02-10 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_user_alive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='kills_this_round',
        ),
    ]
