# Generated by Django 3.1.5 on 2022-02-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_remove_user_kills_this_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kills_this_round',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
