# Generated by Django 3.1.5 on 2022-02-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_user_kills_this_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='death_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='kill_verifying',
            field=models.BooleanField(default=False),
        ),
    ]
